### ISSUE TITLE
MySQL doesnt work on 1.19.3

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Rosewood-Development/PlayerParticles#106]
```
[01:45:49] [Craft Scheduler Thread - 20 - PlayerParticles/INFO]: [PlayerParticles] Data handler connected using MySQL.
[01:45:49] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R2.MinecraftServer
[01:45:49] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[01:45:49] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[01:45:49] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[01:45:49] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[01:45:49] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[01:45:49] [Server thread/WARN]: 	at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:61)
[01:45:49] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:45:49] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[01:45:49] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:45:49] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[01:45:49] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[01:45:49] [Server thread/WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:438)
[01:45:49] [Server thread/WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:173)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01:45:49] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[01:45:49] [Server thread/WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:350)
[01:45:49] [Server thread/WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46)
[01:45:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[01:45:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:45:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1130)
[01:45:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[01:45:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Esophose** [comment]
This looks like it's caused by a PlaceholderAPI issue and not PlayerParticles
