### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by 1640946640** [Rosewood-Development/PlayerParticles#124]
[00:25:42] [Craft Scheduler Thread - 923/WARN]: [PlayerParticles] Plugin PlayerParticles v8.6 generated an exception while executing task 4191
java.lang.NullPointerException: null
        at dev.esophose.playerparticles.manager.DataManager.lambda$loadFixedEffects$9(DataManager.java:261) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-5a600445]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-5a600445]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_371]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_371]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_371]
[00:25:42] [Craft Scheduler Thread - 925/WARN]: [PlayerParticles] Plugin PlayerParticles v8.6 generated an exception while executing task 4192
java.lang.NullPointerException: null
        at dev.esophose.playerparticles.manager.DataManager.lambda$getPPlayer$5(DataManager.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-5a600445]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-5a600445]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_371]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_371]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_371]

**Comment by Esophose** [comment]
This looks like the plugin couldn't connect to your database
