### ISSUE TITLE
projectile is null exception

### ISSUE THREAD

**Issue by iOshawott** [Rosewood-Development/PlayerParticles#82]
```
[12:46:29 WARN]: [PlayerParticles] Plugin PlayerParticles v7.21 generated an exception while executing task 320
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Projectile.getShooter()" because "projectile" is null
        at dev.esophose.playerparticles.styles.ParticleStyleArrows.getParticles(ParticleStyleArrows.java:55) ~[?:?]
        at dev.esophose.playerparticles.manager.ParticleManager.getParticlesWithPlayer(ParticleManager.java:278) ~[?:?]
        at dev.esophose.playerparticles.manager.ParticleManager.displayParticles(ParticleManager.java:263) ~[?:?]
        at dev.esophose.playerparticles.manager.ParticleManager.run(ParticleManager.java:196) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-23]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Airplane-23]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Airplane-23]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
Server Airplane-Purpur-23 1.17.1 
PlayerParticles v7.21

**Comment by Esophose** [comment]
Should be fixed in the latest versions, meant to close this a long while ago.
