### ISSUE TITLE
`Cannot load configuration from stream` error on fresh installation of v7.4

### ISSUE THREAD

**Issue by ASchneider-GitHub** [Rosewood-Development/PlayerParticles#89]
This error is being thrown by an unmodified version of PlayerParticles v7.4 It's the only plugin used on the server instance:

```
[00:32:19] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 1, column 1:
    PlayerParticles_COMMENT_0: ' Che ... 
    ^
expected <block end>, but found '<scalar>'
 in 'reader', line 8, column 3:
      me get statistics on how the plu ... 
      ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:333) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at dev.esophose.playerparticles.config.CommentedFileConfiguration.<init>(CommentedFileConfiguration.java:18) ~[?:?]
	at dev.esophose.playerparticles.config.CommentedFileConfigurationHelper.getNewConfig(CommentedFileConfigurationHelper.java:50) ~[?:?]
	at dev.esophose.playerparticles.config.CommentedFileConfiguration.loadConfiguration(CommentedFileConfiguration.java:25) ~[?:?]
	at dev.esophose.playerparticles.manager.ConfigurationManager.reload(ConfigurationManager.java:341) ~[?:?]
	at dev.esophose.playerparticles.PlayerParticles.getManager(PlayerParticles.java:96) ~[?:?]
	at dev.esophose.playerparticles.PlayerParticles.reload(PlayerParticles.java:124) ~[?:?]
	at dev.esophose.playerparticles.PlayerParticles.onEnable(PlayerParticles.java:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3413-Spigot-862678e-13670b4]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3413-Spigot-862678e-13670b4]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3413-Spigot-862678e-13670b4]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3413-Spigot-862678e-13670b4]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3413-Spigot-862678e-13670b4]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3413-Spigot-862678e-13670b4]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3413-Spigot-862678e-13670b4]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 1, column 1:
    PlayerParticles_COMMENT_0: ' Che ... 
    ^
expected <block end>, but found '<scalar>'
 in 'reader', line 8, column 3:
      me get statistics on how the plu ... 
      ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:282) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:102) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 20 more
[00:32:19] [Server thread/WARN]: java.lang.NoSuchFieldException: yamlOptions
[00:32:19] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[00:32:19] [Server thread/WARN]: 	at dev.esophose.playerparticles.config.CommentedFileConfiguration.getConfigAsString(CommentedFileConfiguration.java:79)
[00:32:19] [Server thread/WARN]: 	at dev.esophose.playerparticles.config.CommentedFileConfiguration.save(CommentedFileConfiguration.java:58)
[00:32:19] [Server thread/WARN]: 	at dev.esophose.playerparticles.config.CommentedFileConfiguration.save(CommentedFileConfiguration.java:54)
[00:32:19] [Server thread/WARN]: 	at dev.esophose.playerparticles.manager.ConfigurationManager.reload(ConfigurationManager.java:358)
[00:32:19] [Server thread/WARN]: 	at dev.esophose.playerparticles.PlayerParticles.getManager(PlayerParticles.java:96)
[00:32:19] [Server thread/WARN]: 	at dev.esophose.playerparticles.PlayerParticles.reload(PlayerParticles.java:124)
[00:32:19] [Server thread/WARN]: 	at dev.esophose.playerparticles.PlayerParticles.onEnable(PlayerParticles.java:59)
[00:32:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:32:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[00:32:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[00:32:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526)
[00:32:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440)
[00:32:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
[00:32:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[00:32:19] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262)
[00:32:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
[00:32:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[00:32:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:32:19] [Server thread/INFO]: [PlayerParticles] Data handler connected using SQLite.
```

`/version` output:
```
[Server thread/INFO]: This server is running CraftBukkit version 3413-Spigot-862678e-13670b4 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
```

**Comment by Esophose** [comment]
Please update to the latest plugin version, this was fixed a while ago but you're severely outdated
