### ISSUE TITLE
getShooter() NPE

### ISSUE THREAD

**Issue by HexedHero** [Rosewood-Development/PlayerParticles#93]
```
[18:37:21 WARN]: [PlayerParticles] Plugin PlayerParticles v7.23 generated an exception while executing task 3640
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Projectile.getShooter()" because "projectile" is null
        at dev.esophose.playerparticles.styles.ParticleStyleArrows.getParticles(ParticleStyleArrows.java:55) ~[?:?]
        at dev.esophose.playerparticles.manager.ParticleManager.getParticlesWithPlayer(ParticleManager.java:278) ~[?:?]
        at dev.esophose.playerparticles.manager.ParticleManager.displayParticles(ParticleManager.java:263) ~[?:?]
        at dev.esophose.playerparticles.manager.ParticleManager.run(ParticleManager.java:196) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Esophose** [comment]
Already fixed in latest version
